bridge/src/lib.rs, cli/src/main.rs
Reproduced on the latest (396198781d48de8561013445d0dc2703a2a503b6) POA master branch.
__Steps to reproduce:__
1. Run two Parity-based nodes responsible for Home and Foreign chains.
2. Run bridge: `RUST_LOG=info bridge --config ... --database ...`.
3. Kill parity process responsible for Foreign chain.
__Expected results:__
The bridge handles gracefully death of Parity node: warns about the connection lose, shutdowns all operations (`deposit_relay`, `withdraw_confirm` and `withdraw_relay`) for a while, waits when the connection appears and runs all operations after that. 
__Actual results:__
After killing Parity process the following appear in the terminal where the bridge is running:
```
WARN:<unknown>: Unexpected IO error: Error { repr: Os { code: 32, message: "Broken pipe" } }
```
No …
=> Problem: bridge dies when Parity is stopped

Cargo.lock, bridge/src/app.rs, bridge/src/bridge/mod.rs, bridge/src/error.rs, cli/Cargo.toml, cli/src/main.rs, examples/supervisor
Currently, bridge will try to handle errors in some
way in order to attempt to restore its functionality.
However, this limits as to how the errors can be handled
as every time a change in handling is needed, a patch
for bridge will needed.
Overtime, this will inevitably grow into a full-fledged
supervisor.
However, there are already supervisor programs out there
(starting from all-encompassing systemd down to small
supervision utilities)
Solution: revert the handling of errors to the old behaviour
but (very importantly) make bridge return meaningful error
codes for all known error types so that the supervisor
can make a proper decision as to what has to be done
(restart, delayed restart, permanent shutdown, notification,
etc.)
=> Problem: complexity associated with error handling

Cargo.lock, bridge/src/api.rs, bridge/src/bridge/balance.rs, bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/mod.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs, bridge/src/error.rs, cli/Cargo.toml, cli/src/main.rs, integration-tests/bridge_config_gas_price.toml, integration-tests/tests/insufficient_funds.rs
Currently there are two possible situations related to low balance on
the account which is used for bridge operations:
1. The account which is used to sign transactions to be addressed by
ForeignBridge contract has low balance. So, the bridge is not able to do
deposit_relay and withdraw_confirm.
2. The account which is used to sign transactions to be addressed by
HomeBridge contract has low balance. So, the bridge is not able to do
withdraw_relay.
In both cases bridges hangs silently at the moment of sending
transactions and does not proceed with further actions even the
operation is intended to be performed in opposite direction (e.g. the
bridge hangs at the moment to perform withdraw_relay, so deposit_relay
cannot be performed either).
Solution: make bridge track its balance and hande …
=> Problem: bridge crashes with insufficient balance

tests/src/lib.rs, tests/tests/deposit_relay.rs, tests/tests/withdraw_confirm.rs, tests/tests/withdraw_relay.rs
Solution: use an updated version of the API
to make them compile
=> Problem: non-integration tests don't compile

Cargo.lock, bridge/Cargo.toml, bridge/src/api.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/lib.rs
If a node configured as Foreign for the bridge and it has no validator
account unlocked the bridge crashes and produces the following message:
```
INFO:bridge::bridge::withdraw_confirm: got 1 new withdraws to sign
INFO:bridge::bridge::withdraw_confirm: withdraw is ready for signature
submission. tx hash 0x6493…4fa8
INFO:bridge::bridge::withdraw_confirm: signing
WARN:bridge: Bridge crashed with Error(Transport("Unexpected response
status code: 405 Method Not Allowed"), State { next_error: None,
backtrace: None })
Error(Transport("Unexpected response status code: 405 Method Not
Allowed"), State { next_error: None, backtrace: None })
```
Solution: sign messages locally
Closes #49
=> Problem: withdraw_confirm failure

Cargo.lock, bridge/Cargo.toml, bridge/src/api.rs, bridge/src/bridge/deploy.rs, bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/mod.rs, bridge/src/bridge/nonce.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs, bridge/src/config.rs, bridge/src/error.rs, bridge/src/lib.rs, cli/src/main.rs
Unfortunately, bridge will still reuse nonce very often.
Specifically when trying to send more than one transaction at
a time, clearly a faulty behaviour.
Solution: chain retrieving a nonce with subsequent sending
of the transaction.
However, chaining these is not enough as it'll still fail.
This is happening because bridge module is polling all its components
(deposit_relay, withdraw_confirm, withdraw_relay) sequentially,
and some of them maybe waiting on their transactions to go through.
However, those transactions are also done as composed futures of nonce
retrieval and transaction sending. This means that it is very often
that first, these futures will go through the nonce acquisition process,
get the same values, and then submit transactions with the same nonce.
This patch makes …
=> Problem: nonce reuse

Makefile, README.md, bridge/Cargo.toml, bridge/src/bridge/deploy.rs, bridge/src/config.rs, cli/Cargo.toml, cli/src/main.rs, integration-tests/Cargo.toml, integration-tests/tests/basic_deposit_then_withdraw.rs, integration-tests/tests/insufficient_funds.rs
Bridge's contracts are now developed in a separate repository
and have their own deployment procedure:
https://github.com/poanetwork/poa-parity-bridge-contracts
However, our integration tests are not yet updated to
use this deployment procedure.
Solution: disable deployment compile-time by default
and only use it in integration tests as a stopgap measure
until the new deployment procedure (or any other viable
alternative) has been used.
=> Problem: bridge should not deploy its contracts anymore

bridge/src/config.rs
It is only necessary when deploying
Solution: remove the requirement for this configuration option
but leave it for the `deploy` feature used in integration tests
until they are rewritten to use external deployment mechanics.
=> Problem: `contract` configuration is no longer necessary

contracts/README.md
Contracts in the repo are not used for the bridge any more.
So, in order to reduce number of questions in the future, a note to reflect the status of contracts is added.
=> added README to reflect that contracts are for integration tests only

README.md, bridge/src/app.rs, bridge/src/bridge/balance.rs, bridge/src/bridge/chain_id.rs, bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/mod.rs, bridge/src/bridge/nonce.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs, bridge/src/config.rs, cli/src/main.rs
This is because it is limiting them to one at a time
per operation type. This was done so that there's no
gaps in nonces due to undelivered transactions.
Solution: allow concurrent sending of transactions
By default, 100 transactions are allowed.
Note, however, that now there's a chance that nonce
gaps may be formed under cerain circumstances.
=> Problem: bridge sends out transactions slowly

cli/src/main.rs
The current behavior for logs displayed during the bridge initialization
is not consistent - home url is reported whereas foreign url is not.
Solution: report it
Fixes #69
=> Problem: Foreign RPC URL is not reported in the logs

bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/mod.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs, bridge/src/error.rs, bridge/src/lib.rs, cli/src/main.rs
If the error like this appears in the logs:
```
INFO:bridge::bridge::withdraw_confirm: waiting for new withdraws that
should get signed
WARN:bridge: Bridge crashed with Error(Transport("Incomplete"), State {
next_error: None, backtrace: None })
Error(Transport("Incomplete"), State { next_error: None, backtrace: None
})
```
it is hard to understand which side of the bridge failed. The message
must contains type of operation (`deposit_relay`, `withdraw_confirm` or
`withdraw_relay`) and side of bridge (URL of RPC channel).
Solution: record error's top level context and print it out if recorded
Addresses #75
=> Problem: errors do not show their context

Cargo.lock, bridge/Cargo.toml, bridge/build.rs
**Problem**: not enforcing a minimum required rustc version could lead to build-time errors.
**Solution**: add a mechanism to enforce a minimum required rustc version in the bridge's build script.
=> Problem: not enforcing a minimum required rustc version could lead to build-time errors

README.md, examples/config.toml
**Problem**: the readme and example config TOML files include obsolete gas-price config options.
**Solution**: remove the old config options, document the new gas-price config options.
=> Problem: the readme and example config TOML files include obsolete gas-price config options

README.md, bridge/src/app.rs, bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/gas_price.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs, bridge/src/config.rs
Solution: fix the maximum number of concurrent HTTP request
at a transport level.
It is set by default to 64 and there's now a new configuration
parameter (`concurrent_http_requests`) in `home` and `foreign`
sections. Previously used `concurrency` parameter from transactions
configuration has been removed.
=> Problem: slow performance and regular timeouts sending transactions

bridge/src/bridge/deposit_relay.rs, bridge/src/bridge/mod.rs, bridge/src/bridge/withdraw_confirm.rs, bridge/src/bridge/withdraw_relay.rs
chance of loss of database updates that would cause it to redo
transactions it already did.
Let's say we've got some database updates through deposit relaying:
https://github.com/poanetwork/poa-bridge/blob/master/bridge/src/bridge/mod.rs#L164-L165
Then, during relaying withdrawals, an error happened:
https://github.com/poanetwork/poa-bridge/blob/master/bridge/src/bridge/mod.rs#L171-L172
This means that we won't reach
https://github.com/poanetwork/poa-bridge/blob/master/bridge/src/bridge/mod.rs#L185-L193
to save the result.
Also, in a similar vein, if one of these streams was to end
(`Ready(None)`) we'd experience a similar loss of updates:
https://github.com/poanetwork/poa-bridge/blob/master/bridge/src/macros.rs#L5
Solution: refactor bridge into two streams, splitting responsibilities
One …
=> Problem: potential loss of database updates

Cargo.lock, cli/Cargo.toml, cli/build.rs, cli/src/main.rs
Solution: introduce `bridge -v|--version` flag to print the version
The version is built off `git describe`, however, as a backup,
if `git describe` fails (stripped .git, etc.), this will fall back
to whatever is specified in Cargo.toml
Fixes #87
=> Problem: hard to check which version the bridge is

README.md, bridge/src/config.rs, examples/config.toml
Solution: make it only accessible when `deploy` feature is on
(for integration tests)
=> Problem: authorities.accounts config setting is obsolete

README.md, bridge/src/config.rs, bridge/src/error.rs, cli/src/main.rs, integration-tests/tests/basic_deposit_then_withdraw.rs, integration-tests/tests/insufficient_funds.rs
Solution: by default, disallow use of non-TLS RPC endpoints
For testing, there's an escape hatch of a command line
argument `--allow-insecure-rpc-endpoints` (purposefully
long) that will reduce the severity of using a non-TLS
RPC endpoint to a warning in a log file.
It was not made to be a configuration file option to reduce
the risk of this option slipping into a production configuration
file by mistake.
Closes #79
=> Problem: insecure RPCs are subject to MITM attacks

README.md, examples/config.toml
It's confusing that gas price oracle is used on the
home side of the bridge, as opposed to the foreign one,
because gas price is fixed on POA.
Solution: flip the gas price configuration example between sides
=> Problem: gas price configuration in examples

examples/config.toml
The names of configuration parameters in `transactions` section were incorrect. So, the example of configuration file is not usable.
=> fixed names of configuration parameters in transactions section
